### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by ptcNN** [Wandang/TwitchPlaysAutoChess#13] opened 2019-04-18 12:23 UTC
Move, Sell, !aa

if I use !aa or !bb etc. command before open shop and then not selected chess piece and then click chess area, and close shop. 
!aa right/top/bot/left : Miss click first bench hero, mouse goes to g3 directions. if already use g3 random hero, select this hero and move around h5. Sometimes Move command doesn't work and Move commend already use mouse click symbol.

I think click very fastly. 0.2 point delay work this sitatuion.

!move AA A1..H8 Game says; Not selected or not move. 

!l and !shop on/off doesn't click show shop and lock. 

pick,item,sell,grap,reroll,Xp,accept,ragequit,search works perfectly.

**Comment by Wandang** [comment] 2019-04-18 14:18
Thanks for another report. I will test !aa + direction

did you use `!move AA A1` ?

!l and !shop on/off worked for me. which resolution are you using?

**Comment by ptcNN** [comment] 2019-04-18 14:29
I use 1920x1080 resolution and Full screen. 

Yes I have use `!move AA A1`  but bot cannot select AA hero. Game is error and say, `Not Selected` Also, game moving command actived stay in game. The next command automatically failed. Bcs, move command active. This my move problem.

**Comment by Wandang** [comment] 2019-04-18 14:42
~Ah I see, probably because the courier/chicken is not selected beforehand and therefore your currently selected unit has no usable ability.~
Nevermind, that is not possible since the courier/chicken is focused before every command. At least it should be

I wrote a testfunction to debug faster. I adjusted the time between mouseclicks to 0.5 because below it sometimes would not work. I had no trouble using `!move AA A1`

Could you write me your used commands so I can try to reproduce the movement error? Like this:
```
!tab 1
!p 2
!aa
!p 3
!m aa a1
```

**Comment by ptcNN** [comment] 2019-04-18 15:08
I'm not using Alt+tab func. 
```
!p 2
!m aa a2
!move aa a2
!aa
!aa bot
!m bb f3
!shop on
```

!p 2
!m aa A2  // *Error: No target *
!aa // *Click middle once, AA area miss click*
!aa bot 
!m bb f3 // *No target and 3 dota error bips* 
!shop on // *Mouse goes to shop button but not click*

**Comment by Wandang** [comment] 2019-04-18 15:20
Did you use `!tab <your placement number>` at the start to calibrate the camera?

For example `!tab 1` if you are first place at the moment

I was not able to reproduce those errors.

I am sorry that the documentary is so bad at the moment. !calib command was abandoned because keyboard usage was broken on windows. That's why every input is done via mouse right now

**Comment by ptcNN** [comment] 2019-04-18 15:32
I can use keybord press `1` when game is start. I can try tab functions.

Okey. I tested tab func. 
```
!m aa a2
!aa
```
Those command works clearly. But this use sqeunce mouse localtion goes outside the chessboard.

```
!p 2
!aa
!p 1
!aa
```
mouse commands are working incorrectly because the already field is used.

**Comment by Wandang** [comment] 2019-04-18 17:11
Ah I see what your problem is.

So what happens is the following (for the movement part):

- Mouse clicks on ability/spell
- Mouse clicks on unit/chess to move
- Mouse clicks on target location (in case of `!aa` it is D3)
- Mouse clicks outside chessboard to lose focus of units, to fix an autochess glitch (normal players have this glitch as well) and to have the mouse at a position where it does not overlay any action.

When the field (in this case D3) is already used the next unit/chess will be placed near it.

**Comment by Wandang** [comment] 2019-04-23 09:34
Closing for now since it seems fixed on my end. If any problems persist don't hesitate to create a new issue or comment here

**Closed as completed by Wandang** 2019-04-23 09:34 UTC
Labels: bug, question
